sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: vm2.lan.luoxianjun.com
    port: 3306
    database: sky_take_out
    username: luo
    password: I_4f2_FWPY_tQYb7

  minio:
    endpoint: https://minio.lan.luoxianjun.com
    accessKey: wLr3WyH7QRkYbmVs83HH
    secretKey: hgAwbBTGD2wcLmDCklVPIibK1qSg2F4V81pCiq11

  redis:
    host: vm2.lan.luoxianjun.com
    port: 6379
    password: password123456
    database: 1

  wechat:
    appid: ******
    secret: ******

